they will have many features 

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

IMPORT THE DATASET

In [3]:
dataset = pd.read_csv('50_Startups.csv')
x= dataset.iloc[:,:-1].values
y= dataset.iloc[:,-1].values
print(x.flatten)
print(y.flatten)

<built-in method flatten of numpy.ndarray object at 0x0000024FACC1E190>
<built-in method flatten of numpy.ndarray object at 0x0000024FA9ADF510>


ENCODE THE CATEGORICAL DATA   - cit location in the dataset which is the categorical data

In [4]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[-1])],remainder = 'passthrough')
x = np.array(ct.fit_transform(x))
#print(x)

In [5]:
from sklearn.model_selection import  train_test_split

x_train, x_test, y_train, y_test =train_test_split(x,y,train_size=0.8,random_state=1)
print(x_test)
print(y_test)

[[0.0 0.0 1.0 72107.6 127864.55 353183.81]
 [0.0 0.0 1.0 46014.02 85047.44 205517.64]
 [1.0 0.0 0.0 28754.33 118546.05 172795.67]
 [0.0 0.0 1.0 20229.59 65947.93 185265.1]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 0.0 1.0 542.05 51743.15 0.0]
 [0.0 0.0 1.0 65605.48 153032.06 107138.38]
 [0.0 1.0 0.0 1315.46 115816.21 297114.46]
 [0.0 0.0 1.0 61136.38 152701.92 88218.23]]
[105008.31  96479.51  78239.91  81229.06 191050.39 182901.99  35673.41
 101004.64  49490.75  97483.56]


IN MULTIPLE LINEAR REGRESSINF THERE IS NOT NEED TO TAKE ANY FEATURE SCALLING 

BECAUSE
IN THE EQUATION OF THE MULTIPLE LINEAR REGRESSION WE HAVE COEFFIECTENT WILL COMPENSTATE THE EACH VALUE SO THERE IS NO NEED FOR IT TO DO FEATURE SCALLING

NO NEED TO CHECK THE FEATURES OF LINEAR REGRESSSION


In [6]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)
y_pred = regressor.predict(x_test)
print(y_pred)
print(y_test)



[114664.41715868  90593.1553162   75692.84151574  70221.88679651
 179790.25514874 171576.92018522  49753.58752028 102276.65888936
  58649.37795761  98272.0256113 ]
[105008.31  96479.51  78239.91  81229.06 191050.39 182901.99  35673.41
 101004.64  49490.75  97483.56]


FINDING THE ACCURACY OF THE MODEL

In [7]:
from sklearn.metrics import r2_score
print(r2_score(y_test,y_pred))


0.9649618042060807


In [8]:

np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[114664.42 105008.31]
 [ 90593.16  96479.51]
 [ 75692.84  78239.91]
 [ 70221.89  81229.06]
 [179790.26 191050.39]
 [171576.92 182901.99]
 [ 49753.59  35673.41]
 [102276.66 101004.64]
 [ 58649.38  49490.75]
 [ 98272.03  97483.56]]


TRYING THIS OUT USING THE POLYNOMIAL REGRESSION


In [9]:
import joblib
joblib.dump(regressor,'Multiple-regression-model.h5')

['Multiple-regression-model.h5']