they will have many features 

In [56]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

IMPORT THE DATASET

In [57]:
dataset = pd.read_csv('50_Startups.csv')
x= dataset.iloc[:,:-1].values
y= dataset.iloc[:,-1].values
print(x.flatten)
print(y.flatten)

<built-in method flatten of numpy.ndarray object at 0x000001F78CCA9170>
<built-in method flatten of numpy.ndarray object at 0x000001F78FAC6310>


ENCODE THE CATEGORICAL DATA   - cit location in the dataset which is the categorical data

In [58]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[-1])],remainder = 'passthrough')
x = np.array(ct.fit_transform(x))
#print(x)

In [59]:
from sklearn.model_selection import  train_test_split

x_train, x_test, y_train, y_test =train_test_split(x,y,train_size=0.8,random_state=50)
print(x_test)
print(y_test)

[[0.0 1.0 0.0 66051.52 182645.56 118148.2]
 [1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 101913.08 110594.11 229160.95]
 [0.0 1.0 0.0 27892.92 84710.77 164470.71]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 72107.6 127864.55 353183.81]
 [0.0 0.0 1.0 20229.59 65947.93 185265.1]
 [0.0 0.0 1.0 61136.38 152701.92 88218.23]
 [0.0 1.0 0.0 73994.56 122782.75 303319.26]
 [0.0 1.0 0.0 142107.34 91391.77 366168.42]]
[103282.38 144259.4  146121.95  77798.83 191050.39 105008.31  81229.06
  97483.56 110352.25 166187.94]


IN MULTIPLE LINEAR REGRESSINF THERE IS NOT NEED TO TAKE ANY FEATURE SCALLING 

BECAUSE
IN THE EQUATION OF THE MULTIPLE LINEAR REGRESSION WE HAVE COEFFIECTENT WILL COMPENSTATE THE EACH VALUE SO THERE IS NO NEED FOR IT TO DO FEATURE SCALLING

NO NEED TO CHECK THE FEATURES OF LINEAR REGRESSSION


In [60]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)
y_pred = regressor.predict(x_test)
print(y_pred)
print(y_test)



[103015.20159796 132582.27760815 132447.73845174  71976.09851258
 178537.48221056 116161.24230167  67851.69209676  98791.73374687
 113969.43533014 167921.06569551]
[103282.38 144259.4  146121.95  77798.83 191050.39 105008.31  81229.06
  97483.56 110352.25 166187.94]


FINDING THE ACCURACY OF THE MODEL

In [61]:
from sklearn.metrics import r2_score
print(r2_score(y_test,y_pred))

0.934706847328201
